name: Code standards

on:
  push:
    branches:
      - main
    tags:
      - v*
    paths-ignore:
      - "docs/**"
      - "**.md"
      - ".all-contributorsrc"
  pull_request:
    branches:
      - main
    tags:
      - v*
    paths-ignore:
      - "docs/**"
      - "**.md"
      - ".all-contributorsrc"

jobs:
  standards:
    name: cargo fmt & cargo clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install nightly toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - name: cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all

      - name: cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features -- -D clippy::all
